// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/proto/addressbook/addressbook.proto

package com.github.eulerlcs.hello.api.proto.addressbook;

public interface AddressBookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.eulerlcs.hello.api.proto.addressbook.AddressBook)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.github.eulerlcs.hello.api.proto.addressbook.Person people = 1;</code>
   */
  java.util.List<com.github.eulerlcs.hello.api.proto.addressbook.Person> 
      getPeopleList();
  /**
   * <code>repeated .com.github.eulerlcs.hello.api.proto.addressbook.Person people = 1;</code>
   */
  com.github.eulerlcs.hello.api.proto.addressbook.Person getPeople(int index);
  /**
   * <code>repeated .com.github.eulerlcs.hello.api.proto.addressbook.Person people = 1;</code>
   */
  int getPeopleCount();
  /**
   * <code>repeated .com.github.eulerlcs.hello.api.proto.addressbook.Person people = 1;</code>
   */
  java.util.List<? extends com.github.eulerlcs.hello.api.proto.addressbook.PersonOrBuilder> 
      getPeopleOrBuilderList();
  /**
   * <code>repeated .com.github.eulerlcs.hello.api.proto.addressbook.Person people = 1;</code>
   */
  com.github.eulerlcs.hello.api.proto.addressbook.PersonOrBuilder getPeopleOrBuilder(
      int index);
}
