spring:
  profiles:
    active: postgres-dev

    group:
      mysql-dev:
        - part-common
        - part-mysql-dev
      mysql-prod:
        - part-common
        - part-mysql-prod
      postgres-dev:
        - part-common
        - part-postgres-dev
      postgres-prod:
        - part-common
        - part-postgres-prod
