logging:
  level:
    root: warn

spring:
  profiles:
    group:
      prod:
        - default

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:33062}/${MYSQL_DATABASE:hello}?useUnicode=true&useSSL=true&useCharacterEncoding=utf-8&serverTimezone=GMT%2B9
    username: ${MYSQL_USER:user01}
    password: ${MYSQL_PASSWORD:123456}
#    schema: classpath:db/schema.sql
#    data: classpath:db/data.sql
